"""Mobile devices constants keys"""

ZTE = "ZTE"
XIAOMI = "Xiaomi"
WIKO = "Wiko"
ULEFONE = "uleFone"
TCL = "TCL"
SONY = "Sony"
SHARP = "Sharp"
SAMSUNG = "Samsung"
PANASONIC = "Panasonic"
OPPO = "Oppo"
ONEPLUS = "OnePlus"
NOKIA = "Nokia"
MOTOROLA = "Motorola"
MEIZU = "Meizu"
LG = "LG"
LENOVO = "Lenovo"
HUAWEI = "Huawei"
HTC = "HTC"
BLU = "Blu"
BLACKVIEW = "Blackview"
BBK = "BBK"
ASUS = "Asus"
APPLE = "Apple"
ALCATEL = "Alcatel"
